services:
  mcp_server:
    build: .
    container_name: mcp_server
    secrets:
      - DATABASE_URL    
    ports:
      - "8002:8002"
    environment:
      PYTHONPATH: "src"
      DATABASE_URL_FILE: /run/secrets/DATABASE_URL
    volumes:
      # Mount only source and config for live reload
      - ./main.py:/app/main.py
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ../data_accessor:/app/../data_accessor
    command: hatch run dev:serve

secrets:
  DATABASE_URL:
    file: ./secrets/DATABASE_URL

