services:
  mcp_client:
    build: .
    container_name: mcp_client
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      PYTHONUNBUFFERED: 1
    command: hatch run dev:serve
