[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.117.1",
    "pydantic==2.11.9",
    "ruff>=0.13.2",
    "uvicorn>=0.37.0",
    "fastmcp>=2.12.4",
    "sqlalchemy>=2.0.43",
    "punq>=0.7.0",
    "loguru>=0.7.3",
    "black>=25.9.0",
    "isort>=6.1.0",
    "mypy>=1.18.2",
]

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.12"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.hatch.envs.dev.scripts]
typecheck = "mypy src tests"
format = "python scripts/format.py"
serve = "uvicorn main:app --reload --log-level debug --port 8080"
