[project]
name = "data_accessor"
version = "0.2.7"
description = "Data access solution"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "punq>=0.7.0",
    "pydantic>=2.11.7",
    "sqlalchemy[asyncio]>=2.0.42",
    "sqlparse>=0.5.3",
    "toml>=0.10.2",
    "uvicorn>=0.37.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["src/data_accessor"]
exclude = [
    "__pycache__",
]

[project.optional-dependencies]
dev = [
    "coverage>=7.10.0",
    "black>=23.11.0",
    "isort>=5.12.0",
    "mypy>=1.7.0"
]

[tool.hatch.envs.dev]
dependencies = [
    "coverage>=7.10.0",
    "black>=23.11.0",
    "isort>=5.12.0",
    "mypy>=1.7.0"
]
variables = { PYTHONPATH = "src" }

[tool.hatch.envs.dev.scripts]
test = """
python -m coverage run -m unittest discover -s tests -v && \
python -m coverage report
"""
format = "black src tests && isort src tests"

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise ImportError"
]

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3

[dependency-groups]
dev = [
    "coverage>=7.10.6",
]
